name: Run Puppeteer Script at Specific Times

on:
  schedule:
    # 7:00, 7:15, 7:30, 7:45 (Asia/Ho_Chi_Minh)
    - cron: '0 0 * * *'    # 7:00 AM Asia/Ho_Chi_Minh (UTC 0:00)
    - cron: '15 0 * * *'   # 7:15 AM Asia/Ho_Chi_Minh (UTC 0:15)
    - cron: '30 0 * * *'   # 7:30 AM Asia/Ho_Chi_Minh (UTC 0:30)
    - cron: '45 0 * * *'   # 7:45 AM Asia/Ho_Chi_Minh (UTC 0:45)

    # 8:00, 8:15, 8:30, 8:45 (Asia/Ho_Chi_Minh)
    - cron: '0 1 * * *'    # 8:00 AM Asia/Ho_Chi_Minh (UTC 1:00)
    - cron: '15 1 * * *'   # 8:15 AM Asia/Ho_Chi_Minh (UTC 1:15)
    - cron: '30 1 * * *'   # 8:30 AM Asia/Ho_Chi_Minh (UTC 1:30)
    - cron: '45 1 * * *'   # 8:45 AM Asia/Ho_Chi_Minh (UTC 1:45)

    # 9:00, 9:15, 9:30, 9:45 (Asia/Ho_Chi_Minh)
    - cron: '0 2 * * *'    # 9:00 AM Asia/Ho_Chi_Minh (UTC 2:00)
    - cron: '15 2 * * *'   # 9:15 AM Asia/Ho_Chi_Minh (UTC 2:15)
    - cron: '30 2 * * *'   # 9:30 AM Asia/Ho_Chi_Minh (UTC 2:30)
    - cron: '45 2 * * *'   # 9:45 AM Asia/Ho_Chi_Minh (UTC 2:45)

    # 10:00, 10:15 (Asia/Ho_Chi_Minh)
    - cron: '0 3 * * *'    # 10:00 AM Asia/Ho_Chi_Minh (UTC 3:00)
    - cron: '15 3 * * *'   # 10:15 AM Asia/Ho_Chi_Minh (UTC 3:15)

    # 13:15 (Asia/Ho_Chi_Minh)
    - cron: '15 6 * * *'   # 13:15 PM Asia/Ho_Chi_Minh (UTC 6:15)

    # 19:00 (Asia/Ho_Chi_Minh)
    - cron: '0 12 * * *'   # 19:00 PM Asia/Ho_Chi_Minh (UTC 12:00)

  workflow_dispatch:

jobs:
  run-puppeteer-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    env:
      TZ: 'Asia/Ho_Chi_Minh'

    steps:
    - name: Check current time and timezone
      run: |
        echo "Current date and time on the runner:"
        date
        echo "Timezone info:"
        timedatectl

    - name: Log scheduled time
      run: |
        echo "Workflow started at: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "Next runs scheduled for:"
        echo "- $(date -d '15 min' '+%Y-%m-%d %H:%M:%S')"
        echo "- $(date -d '30 min' '+%Y-%m-%d %H:%M:%S')"
        echo "- $(date -d '45 min' '+%Y-%m-%d %H:%M:%S')"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install puppeteer googleapis

    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Clear Puppeteer Cache
      run: |
        rm -rf ~/.cache/puppeteer

    - name: Run Puppeteer script
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GOOGLE_CREDENTIALS_VARIABLES: ${{ vars.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
        node index.js
