name: Run Puppeteer Script at Specific Times

on:
  schedule:
    # 7:00, 7:15, 7:30, 7:45
    - cron: '0 0 * * *'
    - cron: '15 0 * * *' 
    - cron: '30 0 * * *'
    - cron: '45 0 * * *'
    # 8:00, 8:15, 8:30, 8:45
    - cron: '0 1 * * *'
    - cron: '15 1 * * *'
    - cron: '30 1 * * *'
    - cron: '45 1 * * *'
    # 9:00, 9:15, 9:30, 9:45
    - cron: '0 2 * * *'
    - cron: '15 2 * * *'
    - cron: '30 2 * * *'
    - cron: '45 2 * * *'
    # 10:00, 10:15
    - cron: '0 3 * * *'
    - cron: '15 3 * * *'
    # 13:15
    - cron: '15 6 * * *'
    # 19:00
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-puppeteer-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    env:
      TZ: 'Asia/Ho_Chi_Minh'

    steps:
    - name: Check current time and timezone
      run: |
        echo "Current date and time on the runner:"
        date
        echo "Timezone info:"
        timedatectl
    - name: Log scheduled time
      run: |
        echo "Workflow started at: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "Next runs scheduled for:"
        echo "- $(date -d '15 min' '+%Y-%m-%d %H:%M:%S')"
        echo "- $(date -d '30 min' '+%Y-%m-%d %H:%M:%S')"
        echo "- $(date -d '45 min' '+%Y-%m-%d %H:%M:%S')"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install puppeteer googleapis

    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Clear Puppeteer Cache
      run: |
        rm -rf ~/.cache/puppeteer

    - name: Run Puppeteer script
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GOOGLE_CREDENTIALS_VARIABLES: ${{ vars.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
        node index.js
